### ISSUE TITLE
Suggestions to avoid duplicate deduction for phase two

### ISSUE THREAD

**Issue by tianhanl** [RaymondJune/csci499_RaymondJune#5]
Missing parameter validation
https://github.com/RaymondJune/csci499_RaymondJune/blob/55b2bfbf262e84c632ce1348d4fe7ee2ce189d88/warble_server.cpp#L42
> -3, reply with invalid ID should fail

https://github.com/RaymondJune/csci499_RaymondJune/blob/55b2bfbf262e84c632ce1348d4fe7ee2ce189d88/warble_server.cpp#L70
> -1, users should not be able to follow themselves

https://github.com/RaymondJune/csci499_RaymondJune/blob/55b2bfbf262e84c632ce1348d4fe7ee2ce189d88/warble_server.cpp#L92
> -5, read non-existing id should fail

The provided usernames need to be checked whether they are registered. (You can abstract this out into a function, since this validation will be used in multiple places)
> -5, unregistered user should not be able to perform commands

**Comment by RaymondJune** [comment]
Hi tianhang,
Thanks for pointing this out and saving me 14 points. I have fixed the issue.
